<#
.SYNOPSIS
  Resolve the newest installed ms-dynamics-smb.al extension's win32 altool.exe (dynamic — survives AL updates).
  Origin: generated by SCXCodex (scx-coder) then hardened for VS Code Insiders + stable. Fixes the
  version-pinned AL-MCP path so bc_al keeps working after AL upgrades.
.EXAMPLE  $altool = Get-KritLatestAltool ; if($altool){ "AL MCP -> $altool" }
#>
function Get-KritLatestAltool {
    [CmdletBinding()] param()
    $roots = @(
        (Join-Path $env:USERPROFILE '.vscode-insiders\extensions'),  # Insiders (this box)
        (Join-Path $env:USERPROFILE '.vscode\extensions')            # stable
    ) | Where-Object { Test-Path $_ }
    $folders = foreach ($r in $roots) { Get-ChildItem $r -Directory -EA SilentlyContinue | Where-Object { $_.Name -like 'ms-dynamics-smb.al-*' } }
    if (-not $folders) { return $null }
    $latest = $folders | Sort-Object {
        $v = ($_.Name -split '-')[-1]
        try { [version]$v } catch { [version]'0.0' }   # robust: malformed version -> lowest
    } -Descending | Select-Object -First 1
    if (-not $latest) { return $null }
    $altool = Join-Path $latest.FullName 'bin\win32\altool.exe'
    if (Test-Path $altool) { return $altool }
    return $null
}
